---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: sms-ghcr-credentials
  namespace: services
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: sms-ghcr-credentials
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: "{{ .dockerconfigjson }}"
  dataFrom:
    - extract:
        key: sms-github-container-registry-auth
