---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: reflector-secret
  namespace: services
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword-connect
    kind: ClusterSecretStore
  dataFrom:
    - extract:
        key: reflector
