---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app qui
  namespace: flux-system
spec:
  targetNamespace: media
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  path: ./kubernetes/apps/media/qui/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: false
  interval: 30m
  retryInterval: 1m
  timeout: 5m
  dependsOn:
    - name: unifi-dns
      namespace: network
    - name: qbittorrent
      namespace: flux-system
  postBuild:
    substitute:
      APP: *app
      VOLSYNC_CLAIM: qui
      VOLSYNC_CAPACITY: 3Gi
    substituteFrom:
      - name: cluster-secrets
        kind: Secret
