apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:T7WW66WTCd0aTUX9jR9MNk9Yn/rNZ8/sTZrf3QzKEgqxqF6cv69Jug==,iv:jjT28BcycZ+52LfrOULFalIDyjwwSr+W2kt8rJr6/OI=,tag:FdBOrPVC4lcwuoju5i4LwA==,type:str]
sops:
  age:
    - recipient: age1nhhe47yy8tsyll5jmpyl3zufvt7n5u0nepaman5na4gh89jfff3qflxded
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxZHljTHFnWnluVjEwQ0lI
        bStOTFE5dUJKUXFKWW05WlBKNmZNYitTNVVFCnBRR1Q3Vnk4VEQrMmQvaWNwRjFm
        d1lPemMrMXB5UFpJTkJ6UnNVN1luOVkKLS0tIFlGMjRjMGNpNkY5UURoL09DazF2
        QWx4SjZobDZJb0hMT0dyOGVCWjNpR3MKZrc5uETV+2i5ewK0MASzvJ6jQJr67LoM
        0XUoAAkbmcoZOIOgUUJiOA6+nI1Dd4ynfAogb/vBP/LVbzt+AtVKyw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-30T20:09:02Z"
  mac: ENC[AES256_GCM,data:3+b8kgubRKLbn6yMZgxbYKbVPzKaAFKBqY2VUiC1qp1tH5p1zynIEVD9MSABjwhUqsTWdzT0QBlcOpwiM6jMQS9dCdvp5p+sKKMDVzjCYVvL0HtV5EIR8c++wxAkOg5HwFxSpiJnYoaavjeZHfbeiOM4gmgxN6ntEexArKMmIjs=,iv:JOoiP2RM4HTbKUiNlhRWq/UYkjSp+G9Ot9VTt7wjAcI=,tag:+icnmbTQpQbNhjqxrOe4Uw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
