---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: victoriametrics
  namespace: monitoring
spec:
  interval: 5m
  chartRef:
    kind: OCIRepository
    name: victoriametrics
  install:
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    fullnameOverride: victoriametrics

    kubeControllerManager:
      enabled: true
      endpoints: []
      service:
        enabled: true
        port: 10257
        targetPort: 10257
        selector:
          component: kube-controller-manager
      vmScrape:
        spec:
          jobLabel: jobLabel
          namespaceSelector:
            matchNames:
              - kube-system
          endpoints:
            - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
              port: http-metrics
              scheme: https
              tlsConfig:
                insecureSkipVerify: true
                caFile: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
                serverName: kubernetes

    grafana:
      enabled: false

    victoria-metrics-operator:
      enabled: true
      operator:
        disable_prometheus_converter: false
        enable_converter_ownership: true

    serviceAccount:
      create: true
      annotations: {}

    defaultRules:
      create: false

    alertmanager:
      enabled: true
      ingress:
        enabled: false
      monzoTemplate:
        enabled: true

      spec:
        disableNamespaceMatcher: true
        externalURL: "https://alrtmngr.${SECRET_DOMAIN}"
        disableRouteContinueEnforce: true

      config:
        global:
          resolve_timeout: 5m
        route:
          group_by: ["alertname"]
          group_wait: 1m
          group_interval: 5m
          repeat_interval: 3h
          receiver: monitoring-slack-slack-monitoring
          routes:
            - receiver: blackhole
              matchers:
                - "severity=blackhole"
              continue: true
        receivers:
          - name: blackhole

    vmalert:
      enabled: true
      remoteWriteVMAgent: false
      spec:
        selectAllByDefault: true
        extraArgs:
          external.alert.source: "?g0.expr={{`{{.Expr|queryEscape}}`}}"
        externalLabels:
          cluster: homelab
          grafana_url: https://grafana.${SECRET_DOMAIN}
        evaluationInterval: 15s
      ingress:
        enabled: false

    vmagent:
      enabled: true
      spec:
        replicaCount: 1
        externalLabels:
          cluster: homelab
        # inlineScrapeConfig: |
        #   - job_name: node-exporter
        #     honor_labels: true
        #     scrape_interval: 1m
        #     scrape_timeout: 10s
        #     metrics_path: /metrics
        #     scheme: http
        #     static_configs:
        #       - targets:
        #           - "10.5.0.32:9100"
        selectAllByDefault: true
        scrapeInterval: 25s
        extraArgs:
          promscrape.streamParse: "true"
      ingress:
        enabled: false

    vmsingle:
      enabled: false

    vmcluster:
      enabled: true
      spec:
        retentionPeriod: "90d"
        vminsert:
          replicaCount: 1
          resources:
            requests:
              cpu: 300m
              memory: 500Mi
            limits:
              memory: 500Mi
          extraArgs:
            maxLabelsPerTimeseries: "80"

        vmstorage:
          replicaCount: 2
          podDisruptionBudget:
            maxUnavailable: 1
          resources:
            requests:
              cpu: 250m
              memory: 10Gi
            limits:
              memory: 10Gi
          storageDataPath: /vm-data
          storage:
            volumeClaimTemplate:
              spec:
                resources:
                  requests:
                    storage: 100Gi
          volumes:
            - name: vmbackup-volume
              secret:
                secretName: vmbackup-secret
          containers:
            - name: vmbackup
              image: victoriametrics/vmbackup:latest
              imagePullPolicy: Always
              args:
                - -dst=s3://backups/victoriametrics
                - -customS3Endpoint=https://5fda75e1262c2da5d9b80e4218045c63.r2.cloudflarestorage.com
                - -snapshotCreateURL=http://localhost:8482/snapshot/create
              env:
                - name: AWS_ACCESS_KEY_ID
                  valueFrom:
                    secretKeyRef:
                      name: vmbackup-secret
                      key: AWS_ACCESS_KEY_ID
                - name: AWS_SECRET_ACCESS_KEY
                  valueFrom:
                    secretKeyRef:
                      name: vmbackup-secret
                      key: AWS_SECRET_ACCESS_KEY
              volumeMounts:
                - name: vmstorage-db
                  mountPath: /storage
                - name: vmbackup-volume
                  mountPath: /backup

        vmselect:
          replicaCount: 2
          podDisruptionBudget:
            maxUnavailable: 1
          resources:
            requests:
              cpu: 300m
              memory: 500Mi
            limits:
              memory: 500Mi

    prometheus-node-exporter:
      enabled: true
    kube-state-metrics:
      enabled: true
    kubelet:
      enabled: true
    kubeApiServer:
      enabled: true
    kubeEtcd:
      enabled: true
    kubeScheduler:
      enabled: true
      endpoints: []
      service:
        enabled: true
        port: 10259
        targetPort: 10259
        selector:
          component: kube-scheduler
      vmScrape:
        spec:
          jobLabel: jobLabel
          namespaceSelector:
            matchNames: [kube-system]
          endpoints:
            - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
              port: http-metrics
              scheme: https
              tlsConfig:
                insecureSkipVerify: true
                caFile: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
