---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vmbackup-secret
  namespace: monitoring
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        AWS_ACCESS_KEY_ID: "{{ .AWS_ACCESS_KEY_ID }}"
        AWS_SECRET_ACCESS_KEY: "{{ .AWS_SECRET_ACCESS_KEY }}"
        SNAPSHOT_CREATE_URL: "{{ .SNAPSHOT_CREATE_URL }}"
  dataFrom:
    - extract:
        key: r2
    - extract:
        key: vmbackup
