apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:bHTDVnT18fw=,iv:fLyUmvl4Z58iuWTBeIt0JDYSpQSjdrAMGcJ573uwDoo=,tag:diMWRCiiBJBuIeHxSkXCXw==,type:str]
sops:
  age:
    - recipient: age1nhhe47yy8tsyll5jmpyl3zufvt7n5u0nepaman5na4gh89jfff3qflxded
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpQkZ5dU13TmQ2SThYRWFi
        YlFOZDh3eFlhYWtUb3h3ZndUWEFrQXNkUkJVCjV1YnBUTGxkRE9MdllSWWFGYjJV
        cTBRbmhHMndjK1RqMzZaSC9nZkFHNEUKLS0tIG9pWDE5R3A0MXJjMTdLWkVlb1dG
        d3JXUy9LZE5JTlVRdkhRUlFMelUySFUKAiUrtqUpRHUWyPhITV8PazY6gDgZIsRv
        KEyOqOqfb1QyoJoU2kwbaF1/9NzGFAzigWlUtlUaCnMIj6VTySof7w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-30T20:09:01Z"
  mac: ENC[AES256_GCM,data:+VSU6m2+vD1Pu9O+8sjAG1c+MjfMl2EJGdYScMsZ6u4seULIxYI+OUo8pMtZQQweOTxyDxOViG27bVXhKXlqGD6vb0+kEbhAc8x55iU8cVI7xsGEpv9RklnFJ56c3MZSuxFthjDhvPB4V3NnlBI6LL6QA2oE7n6s3URPPu6KuOo=,iv:GV6T9I2NBL5sBwKr0wFHBf5RSTd/RrzqGd3j0gFKD9g=,tag:cKuk2rg4Z8EIkGRd5/UUrw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
