apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:bHTDVnT18fw=,iv:fLyUmvl4Z58iuWTBeIt0JDYSpQSjdrAMGcJ573uwDoo=,tag:diMWRCiiBJBuIeHxSkXCXw==,type:str]
    SECRET_DOMAIN_SMS: ENC[AES256_GCM,data:c24OjT3DoVZAhnarSNZhkWs=,iv:+iUBO3cXnlfDLl3d3/MuMsNYDR1uYAhQcQsIQj+ohPE=,tag:8pFnX423QErK6TFg7RTBtw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpQkZ5dU13TmQ2SThYRWFi
            YlFOZDh3eFlhYWtUb3h3ZndUWEFrQXNkUkJVCjV1YnBUTGxkRE9MdllSWWFGYjJV
            cTBRbmhHMndjK1RqMzZaSC9nZkFHNEUKLS0tIG9pWDE5R3A0MXJjMTdLWkVlb1dG
            d3JXUy9LZE5JTlVRdkhRUlFMelUySFUKAiUrtqUpRHUWyPhITV8PazY6gDgZIsRv
            KEyOqOqfb1QyoJoU2kwbaF1/9NzGFAzigWlUtlUaCnMIj6VTySof7w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nhhe47yy8tsyll5jmpyl3zufvt7n5u0nepaman5na4gh89jfff3qflxded
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-04T19:46:08Z"
    mac: ENC[AES256_GCM,data:r/Fm94Ty0Vz/b6VbCHLUWZ8XLcAFijAbng94uSZimHO2K0tYgE/dUJzry+uw/PJ5UynFVY4Yx3rFI9MWdB+1FqGc2mHjhG2H5T+pLFFcDznFiXsydkrnFLe86xafLTcOo9IDDtBWyRmQHL9D1zjnKgOLl2vH3bNztkoLMnB/8oE=,iv:DVmUTh9tWdFJcqjd8dvTYY7v62GghFYPcnYy6HDO7sY=,tag:QUlx4jSlPMlx9Vfm/QNykA==,type:str]
    mac_only_encrypted: true
    version: 3.13.1
