apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:pKFI3GO676ZF35JvcyjEWtM0kAUOOqf8fT4qR9dDs5Y=,iv:6AjPfNKDPIUXtkydHXYJLcHB+Sli08Loemss1/OqFn0=,tag:EnWntHI5YZxfnau8XUD7gA==,type:str]
sops:
  age:
    - recipient: age1nhhe47yy8tsyll5jmpyl3zufvt7n5u0nepaman5na4gh89jfff3qflxded
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6cFBHdklZRGVqMEkyTWk3
        N2FDSGJwUENxejdUczhSdGlRMDlmOVAwR1Y4CmFwZlppU1dzRnpoUmU2eVNNcG1w
        YjZudmU2WDBxKzA0ZnlKNEZyQ2NlWWMKLS0tIGxYNUt3RWRrUGxJT1hpVlN6aWRG
        US9qNzBhak5TK1I0dnNidC9vWlhHRXMKkTqU3yNZMrZAUaFt0RIlthh7LYjw1Hvy
        dGhTKTsangimwdZZcIocwveRgQjYO+1vebyHPPUSkvS3kvw02RUbHQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-30T20:09:01Z"
  mac: ENC[AES256_GCM,data:trccBoUPHwOB4OMS4i39JFqQAoekBbTvrcWHp1liUWBctBBX7c3a8TX97r+Bwteang0BtVLxBE4YESMpC3IRTVX9Ofvm6cM4XGlFmSeXcjCBkXfzjza/Wm6S6BHsOfw4aaCHipImeiRt2U1izXEtrFkAFqXdwE17F18OXNmG9YU=,iv:7lWdzSE6D8Tnto43ACndp+8B2dyvdpyT7xxMqndrAo0=,tag:+tefgwH3vbsQ+vmnHGUHJw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
