---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./mariadb/ks.yaml
  - ./redis/operator/ks.yaml
  - ./redis/librechat/ks.yaml
  - ./mongodb/operator/ks.yaml
  - ./mongodb/librechat/ks.yaml
