---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./vernemq/ks.yaml
  - ./zigbee2mqtt/ks.yaml
  - ./homeassistant/ks.yaml
  - ./govee2mqtt/ks.yaml
