apiVersion: operator.victoriametrics.com/v1beta1
kind: VMRule
metadata:
  name: smartctl-rules
  namespace: monitoring
spec:
  "groups":
  - "name": |-
      smartctl.rules
    "rules":
    - "alert": |-
        SmartDeviceHighTemperature
      "description": "Mounted drive {{ $labels.device }} on device {{ $labels.instance\
        \ }}\nhas a temperature higher than 80\xB0C.\n"
      "expr": |-
        smartctl_device_temperature > 80
      "for": |-
        15m
      "labels":
        "severity": |-
          critical
    - "alert": |-
        SmartDeviceTestFailed
      "description": |
        Mounted drive {{ $labels.device }} on device {{ $labels.instance }}
        did not pass its SMART test.
      "expr": |
        (
          smartctl_device_smart_status != 1
        or
          smartctl_device_status != 1
        )
      "for": |-
        15m
      "labels":
        "severity": |-
          critical
    - "alert": |-
        SmartDeviceCriticalWarning
      "description": |
        Mounted drive {{ $labels.device }} on device {{ $labels.instance }}
        is in a critical state.
      "expr": |-
        smartctl_device_critical_warning != 0
      "for": |-
        15m
      "labels":
        "severity": |-
          critical
    - "alert": |-
        SmartDeviceMediaErrors
      "description": |
        Mounted drive {{ $labels.device }} on device {{ $labels.instance }}
        has media errors.
      "expr": |-
        smartctl_device_media_errors != 0
      "for": |-
        15m
      "labels":
        "severity": |-
          critical
    - "alert": |-
        SmartDeviceAvailableSpareUnderThreadhold
      "description": |
        Device {{ $labels.device }} on instance {{ $labels.instance }}
        is under available spare threashold.
      "expr": |-
        smartctl_device_available_spare_threshold > smartctl_device_available_spare
      "for": |-
        15m
      "labels":
        "severity": |-
          critical
    - "alert": |-
        SmartDeviceInterfaceSlow
      "description": |
        Device {{ $labels.device }} on instance {{ $labels.instance }}
        interface is slower then it should be.
      "expr": |
        smartctl_device_interface_speed{speed_type="current"} != on(device, instance, namespace, pod) smartctl_device_interface_speed{speed_type="max"}
      "for": |-
        15m
      "labels":
        "severity": |-
          critical
