apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:1pXI8eegxe9hYdSqt43Dn9Z+UMKaxMFAGKs2FnGvtu3HYF0+5icGeCxsau7H0Kma2T3V2SQ9NGB/2hs0cM0AQgHm2v7pOOH2xlWWRPaL0/eAe1YIgWnFT+yZOV3H0kgFG8n7hro/1NnFSX0RcI/wAMDMdx0MaWHUvwWZ8CH8DZmy4E3wjg1FT8Tigla/gXGRbAmsyQWW6RKs4YqKA6FH2AhK6KLEpr+rm5LeMS3jwfMP9EtF,iv:Uxxe2Vj0KwUUbfIDzCpBigBH1aPpVetIH2FwedD5s7E=,tag:gpZ5Xv38SiDIUjRT0uPDrQ==,type:str]
sops:
  age:
    - recipient: age1nhhe47yy8tsyll5jmpyl3zufvt7n5u0nepaman5na4gh89jfff3qflxded
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOQ3FXTmxnSlVpWDJWQm1o
        eDZxYTRxNW1EQnMvYUFSa3RNaGl0eGVublZzCmptUmpnN3JMMWFlRmxrbmUxMWlL
        ZTVNRkhKdkNGTjlOcWpUdmU4QUcxaFkKLS0tIEFONHFmWnJiZisvdDVCWUpBNjlC
        eEtTVXVzb0VJZWdnSnVieTJtbEx6QmcKFY2pmbhvWi8OdTTrA7HFY9mj+fiR0pP/
        AtPKuHgN9E18g0uFKzSpY66KudD47K3lMEiB1NlyaCH/Ei70Ci54JA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-30T20:09:02Z"
  mac: ENC[AES256_GCM,data:0Z9oSuOPD36pkYT2KMmrtEqZMPrNYhk+XIphqByDvvpQOdFXmaXpHiN1kCSggnWJ+Q6jEjjDVOAV19+Ll2EEsZNwQTqxFanB9qDSgb01MzU0xgOHaHin6cJdmvptoZAPZvLK2K7GnKC5D4/+r8MsZQIyTVI+yerT3gT1Qf5iMr0=,iv:+/JCB999sGriyvmc0y8KeNbmQDqu2EE/cidtaQz6DAg=,tag:KIaY7CpI64894dDgl9aXIg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
