---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./snapshot-controller/ks.yaml
  - ./onepassword-connect/ks.yaml
  - ./external-secrets/ks.yaml
  - ./volsync/ks.yaml
  - ./atuin/ks.yaml
