apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:+TOvu5XpRBU3Yhr8gQAvvEBxI2O3bJVQRmgkkK8eVrPj5sTINtKoQw==,iv:C5sjBFoC8P0rComUyZB8uJhMgrOXw/LPevvqL/bsiFY=,tag:7xV9i/VnSYeg4UbGl39pqw==,type:str]
sops:
  age:
    - recipient: age1nhhe47yy8tsyll5jmpyl3zufvt7n5u0nepaman5na4gh89jfff3qflxded
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNV3BRbEJaVjdCVGNKdlRw
        YnhVeitqdDBmd1J6Z1RjLzVIYXg3K1Zwb1E4CldYOWdJTzZtSFlyTGdMV0EzcSsy
        OFhieVIvYXlOSHl3aExUcVVPUUh3M0kKLS0tIHgzZ0VnUWhYU1MwV255aVFjMlJ5
        R3VHZlhBeUwyNWJ3UDQwVGx0YjByYWsKl8tVEqpYwFeAQR1A+zbsWtSDkim1fQa9
        xdlvzHVI/iMEaM9eMzL0/0OGSz02vjNSn2JnpsAJ6ayu9gLnGYT3gQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-30T20:09:02Z"
  mac: ENC[AES256_GCM,data:ogxFfBw45UyWxsrkKQFGGU0HxDLl9+wLz8CVEAMJ5BEHh2mtU7NgXnz5xAl8B8zYi23ILhTAFLnJm3939O7mA0y+VypvGZv9mbBVP4ylr2I0bLN9HRUwH6ebdPdptv1ccdb/DREeC8CTE7p4Mssll3v5JdiiMZfV4iRkX5dlOMU=,iv:g8VrOpMK4w3/K3p2TdCm18t4xo+EQenzu7LHlwlncKg=,tag:Jym8/Ttah8GXhgNkznb4yw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
