---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: librechat-secret
  namespace: services
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: &name librechat-secret
    template:
      engineVersion: v2
      data:
        CREDS_KEY: "{{ .CREDS_KEY }}"
        CREDS_IV: "{{ .CREDS_IV }}"
        JWT_SECRET: "{{ .JWT_SECRET }}"
        JWT_REFRESH_SECRET: "{{ .JWT_REFRESH_SECRET }}"
        MONGO_URI: "{{ .MONGO_URI }}"
        MEILI_MASTER_KEY: "{{ .MEILI_MASTER_KEY }}"
        OPENROUTER_KEY: "{{ .OPENROUTER_KEY }}"
        AWS_ACCESS_KEY_ID: "{{ .AWS_ACCESS_KEY_ID }}"
        AWS_SECRET_ACCESS_KEY: "{{ .AWS_SECRET_ACCESS_KEY }}"
        AWS_BUCKET_NAME: "{{ .AWS_BUCKET_NAME }}"
  dataFrom:
    - extract:
        key: librechat
    - extract:
        key: meilisearch
