---
apiVersion: k8s.mariadb.com/v1alpha1
kind: User
metadata:
  name: invoiceninja
  namespace: database
spec:
  mariaDbRef:
    name: mariadb-galera
  passwordSecretKeyRef:
    name: mariadb-secret
    key: INVOICENINJA_PASSWORD
  maxUserConnections: 20
